name: Save Environment Variables
description: Saves all environment variables such that they can be restored later.
outputs:
  json:
    description: The json dictionary from which to restore environment variables later.
    value: ${{ steps.compute-output.outputs.json }}
runs:
  using: "composite"

  steps:
  - name: Compute output
    id: compute-output
    shell: pwsh
    run: |
      $ErrorActionPreference = "Stop"
      $Json = [Environment]::GetEnvironmentVariables() | ConvertTo-Json -Compress
      Add-Content -Path $Env:GITHUB_OUTPUT -Value "json=$Json" -Encoding utf8