name: Setup Swift
description: Installs dependencies and setups the environment for building Swift code on Windows.
runs:
  using: "composite"

  steps:
  - name: Setup Visual Studio Development Environment
    uses: compnerd/gha-setup-vsdevenv@main

  - name: Install Swift
    uses: compnerd/gha-setup-swift@81f383b35a86e6e966de139be25b451d4f7dd953 # The next main commit breaks our %Path%
    with:
      branch: swift-5.10.1-release
      tag: 5.10.1-RELEASE