#include "windows/BaseTsd.h"
#include "windows/combaseapi.h"
#include "windows/guiddef.h"
#include "windows/oaidl.h"
#include "windows/objidl.h"
#include "windows/oleauto.h"
#include "windows/unknwn.h"