import CodeWriters

internal func writeGeneratedCodePreamble(to writer: SwiftSourceFileWriter) {
    writer.writeCommentLine("Generated by swift-winrt")
    writer.writeCommentLine("swiftlint:disable all", groupWithNext: false)
}