import "MinimalTypes.idl";

namespace TestComponent
{
	interface IEvent
	{
		event MinimalDelegate Event;
		void Fire();
	};

	interface IEventCounter
	{
		Int32 Count { get; };
		void Detach();
	};

	static runtimeclass Events
	{
		static IEvent Create();
		static IEventCounter CreateCounter(IEvent inner);
	};
}