#include "MinimalTypes.idl"

namespace WinRTComponent
{
    interface IMultiOutParams
    {
        // Regression test for https://github.com/tristanlabelle/swift-winrt/issues/340
        // The virtual table entry for methods with multiple out params is tricky
        // because it requires supporting rollback if writing the second out param fails.
        void Get(out MinimalClass output0, out MinimalClass output1);
    }
}