// Includes all .idl files so we have a single <Midl Include="All.idl"> entry in the vcxproj.
// This speeds up the build by avoiding multiple midlrt calls followed by an mdmerge step.
#include "Arrays.idl"
#include "ByteBuffers.idl"
#include "Collections.idl"
#include "DateTimes.idl"
#include "Enums.idl"
#include "Errors.idl"
#include "Events.idl"
#include "ForCustomActivationFactoryResolution.idl"
#include "InspectableBoxing.idl"
#include "Int32Wrapper.idl"
#include "InterfaceCasting.idl"
#include "IExposeObservableVector.idl"
#include "IMultiOutParams.idl"
#include "ManualAsyncOperation.idl"
#include "MinimalTypes.idl"
#include "MinimalUnsealedClasses.idl"
#include "NullValues.idl"
#include "Numbers.idl"
#include "ObjectReferencer.idl"
#include "OutputArgument.idl"
#include "OverloadedSum.idl"
#include "ReferenceBoxing.idl"
#include "ReturnArgument.idl"
#include "Strings.idl"
#include "Structs.idl"
#include "SwiftAttributes.idl"
#include "WeakReferencer.idl"