namespace WinRTComponent
{
    enum SignedEnum
    {
        Min = -2147483648,
        NegativeOne = -1,
        Zero = 0,
        One = 1,
        Max = 2147483647
    };

    [flags]
    enum FlagsEnum
    {
        None = 0,
        Bit0 = 1,
        Bit16 = 0x10000,
        All = 0xFFFFFFFF,
    };

    [attributeusage(target_enum)]
    attribute SwiftEnumAttribute {}

    [SwiftEnum]
    enum SwiftEnum
    {
        Zero = 0,
        One = 1
    };

    // Regression test for https://github.com/tristanlabelle/swift-winrt/issues/330
    interface IFlagsEnumParam {
        void Set(FlagsEnum value);
    };
}