import "Arrays.idl";
import "ByteBuffers.idl";
import "Collections.idl";
import "DateTimes.idl";
import "Enums.idl";
import "Errors.idl";
import "Events.idl";
import "ForCustomActivationFactoryResolution.idl";
import "InspectableBoxing.idl";
import "Int32Wrapper.idl";
import "InterfaceCasting.idl";
import "ManualAsyncOperation.idl";
import "MinimalTypes.idl";
import "MinimalUnsealedClasses.idl";
import "NullValues.idl";
import "Numbers.idl";
import "ObjectReferencer.idl";
import "OutputArgument.idl";
import "OverloadedSum.idl";
import "ReferenceBoxing.idl";
import "ReturnArgument.idl";
import "Strings.idl";
import "Structs.idl";
import "SwiftAttributes.idl";
import "WeakReferencer.idl";