#include "MinimalTypes.idl"

namespace WinRTComponent
{
    static runtimeclass Arrays
    {
        // Use an element type involving allocations,
        // and assume that inert elements an other objects behave the same.
        static String GetLast(String[] value);
        static String[] Make(String a, String b);
        static void Output(String a, String b, out String[] array);
        static void SwapFirstLast(ref String[] array);
    };
}