#include "MinimalTypes.idl"

namespace WinRTComponent
{
    static runtimeclass Errors
    {
        static void FailWith(Windows.Foundation.HResult hr, String message);
        static String NotImplementedProperty;
        static void Call(MinimalDelegate callee);
        static Windows.Foundation.HResult CatchHResult(MinimalDelegate callee);
        static String CatchMessage(MinimalDelegate callee);
    };
}