#include "MinimalTypes.idl"

namespace WinRTComponent
{
    interface IEventSource
    {
        event MinimalDelegate Event;
        void Fire();
    };

    interface IEventCounter
    {
        Int32 Count { get; };
        void Detach();
    };

    static runtimeclass Events
    {
        static IEventSource CreateSource();
        static IEventCounter CreateCounter(IEventSource source);
    };
}