import "MinimalTypes.idl";

namespace WinRTComponent
{
    static runtimeclass InspectableBoxing
    {
        static IInspectable BoxInt32(Int32 value);
        static Int32 UnboxInt32(IInspectable value);
        static IInspectable BoxString(String value);
        static String UnboxString(IInspectable value);
        static IInspectable BoxMinimalEnum(MinimalEnum value);
        static MinimalEnum UnboxMinimalEnum(IInspectable value);
        static IInspectable BoxMinimalStruct(MinimalStruct value);
        static MinimalStruct UnboxMinimalStruct(IInspectable value);
        static IInspectable BoxMinimalDelegate(MinimalDelegate value);
        static MinimalDelegate UnboxMinimalDelegate(IInspectable value);
    };
}