namespace WinRTComponent
{
    enum MinimalEnum { Value };
    struct MinimalStruct { Int32 Field; };
    interface IMinimalInterface { void Method(); }
    runtimeclass MinimalClass : [default] IMinimalInterface { MinimalClass(); }
    delegate void MinimalDelegate();
}
