namespace WinRTComponent
{
    unsealed runtimeclass MinimalBaseClass
    {
        MinimalBaseClass();
        overridable String TypeName { get; };

        static MinimalBaseClass CreateBase();
        static MinimalBaseClass CreateDerivedAsBase();
        static MinimalBaseClass CreatePrivate();
        static MinimalBaseClass Passthrough(MinimalBaseClass value);
        static String GetTypeName(MinimalBaseClass value);
    };

    unsealed runtimeclass MinimalDerivedClass : MinimalBaseClass
    {
        MinimalDerivedClass();
        static MinimalDerivedClass CreateDerived();
    };
}