namespace WinRTComponent
{
    unsealed runtimeclass MinimalUnsealedClass
    {
        MinimalUnsealedClass();
        overridable Boolean IsDerived { get; };

        static MinimalUnsealedClass Create();
        static MinimalUnsealedClass CreateDerived();
        static MinimalUnsealedClass Passthrough(MinimalUnsealedClass value);
        static Boolean GetIsDerived(MinimalUnsealedClass value);
    };
}