namespace WinRTComponent
{
	// WinRT structs allow primitives, strings, IReferences, and other such structs.
	struct LeafStruct
	{
		Int32 Int32;
		String String;
		// TODO(#6): Support IReference<T> projection
		// Windows.Foundation.IReference<Int32> Reference;
	};

	struct Struct
	{
		Int32 Int32;
		String String;
		// TODO(#6): Support IReference<T> projection
		// Windows.Foundation.IReference<Int32> Reference;
		LeafStruct Nested;
	};

	static runtimeclass Structs
	{
		static Struct Make(Int32 a, String b, LeafStruct d);

		static Int32 GetInt32(Struct value);
		static String GetString(Struct value);
		static LeafStruct GetNested(Struct value);

		static void Output(Int32 a, String b, LeafStruct d, out Struct value);

		static Struct ReturnRefConstArgument(ref const Struct value);
	};
}