name: All Checks Passed
on:
  pull_request:
    types: [ opened, synchronize, reopened, ready_for_review ]
jobs:
  allchecks:
    name: All Checks Passed
    runs-on: ubuntu-latest
    permissions:
      checks: read
      contents: read
    timeout-minutes: 15
    steps:
      - uses: wechuli/allcheckspassed@v1
        with:
          delay: 6 # minutes
          retries: 1000
          polling_interval: 0.1 # 6 seconds