name: Build (CMake)

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  support:
    name: Support Module
    runs-on: windows-2022
    timeout-minutes: 15

    steps:
    - uses: actions/checkout@v3

    - name: Setup Visual Studio Development Environment
      uses: compnerd/gha-setup-vsdevenv@main

    - name: Install Swift
      uses: compnerd/gha-setup-swift@81f383b35a86e6e966de139be25b451d4f7dd953 # The next main commit breaks our %Path%
      with:
        branch: swift-5.10.1-release
        tag: 5.10.1-RELEASE

    - name: CMake Configure
      shell: pwsh
      run: cmake --preset debug

    - name: CMake Build
      shell: pwsh
      run: cmake --build --preset debug

  generator:
    name: Generator
    runs-on: windows-2022
    timeout-minutes: 15

    steps:
    - uses: actions/checkout@v3

    - name: Setup Visual Studio Development Environment
      uses: compnerd/gha-setup-vsdevenv@main

    - name: Install Swift
      uses: compnerd/gha-setup-swift@81f383b35a86e6e966de139be25b451d4f7dd953 # The next main commit breaks our %Path%
      with:
        branch: swift-5.10.1-release
        tag: 5.10.1-RELEASE

    - name: CMake Configure
      working-directory: Generator
      shell: pwsh
      run: cmake --preset debug

    - name: CMake Build
      working-directory: Generator
      shell: pwsh
      run: cmake --build --preset debug