name: Build & Test

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022
    timeout-minutes: 15

    steps:
    - uses: actions/checkout@v3

    - name: Setup Visual Studio Development Environment
      uses: compnerd/gha-setup-vsdevenv@main

    - name: Install Swift
      uses: compnerd/gha-setup-swift@81f383b35a86e6e966de139be25b451d4f7dd953 # The next main commit breaks our %Path%
      with:
        branch: swift-5.10.1-release
        tag: 5.10.1-RELEASE

    - name: Build code generator
      working-directory: Generator
      shell: pwsh
      run: swift build --verbose --build-tests

    - name: Test code generator
      working-directory: Generator
      shell: pwsh
      run: swift test --verbose --skip-build

    - name: Build support module
      shell: pwsh
      run: swift build --verbose --build-tests

    - name: Test support module
      shell: pwsh
      run: swift test --verbose --skip-build

    - name: Build Test WinRT Component
      working-directory: InteropTests
      shell: pwsh
      run: '& .\BuildWinRTComponent.ps1'

    - name: Build InteropTests
      working-directory: InteropTests
      shell: pwsh
      run: swift build --verbose --build-tests

    - name: Run InteropTests
      working-directory: InteropTests
      shell: pwsh
      run: swift test --verbose --skip-build