name: Build & Test

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  spm-support:
    name: SPM - Support Module
    runs-on: windows-2022
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v3
    - uses: ./.github/actions/setup-swift
    
    - name: Build support module
      shell: pwsh
      run: swift build --verbose --build-tests
    
    - name: Test support module
      shell: pwsh
      run: swift test --verbose --skip-build

  spm-generator-and-interoptests:
    name: SPM - Generator and InteropTests
    runs-on: windows-2022
    timeout-minutes: 15

    steps:
    - uses: actions/checkout@v3
    - uses: ./.github/actions/setup-swift

    - name: Build code generator
      working-directory: Generator
      shell: pwsh
      run: swift build --verbose --build-tests

    - name: Test code generator
      working-directory: Generator
      shell: pwsh
      run: swift test --verbose --skip-build

    - name: Build WinRTComponent
      working-directory: InteropTests
      shell: pwsh
      run: |
        & .\Build-WinRTComponentProjection.ps1 -SwiftWinRT "$Env:GITHUB_WORKSPACE\Generator\.build\debug\SwiftWinRT.exe"

    - name: Build InteropTests
      working-directory: InteropTests
      shell: pwsh
      run: swift build --verbose --build-tests

    - name: Run InteropTests
      working-directory: InteropTests
      shell: pwsh
      run: swift test --verbose --skip-build

  cmake:
    name: CMake - All (No Tests)
    runs-on: windows-2022
    timeout-minutes: 15

    steps:
    - uses: actions/checkout@v3
    - uses: ./.github/actions/setup-swift

    - name: CMake Configure
      shell: pwsh
      run: cmake --preset debug

    - name: CMake Build
      shell: pwsh
      run: cmake --build --preset debug
