name: Build & Test

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  support-spm:
    name: Support Module (SPM)
    runs-on: windows-2022
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v3
    - uses: ./.github/actions/setup-swift
    
    - name: Build support module
      shell: pwsh
      run: swift build --verbose --build-tests
    
    - name: Test support module
      shell: pwsh
      run: swift test --verbose --skip-build

  generator-and-interoptests-spm:
    name: Generator and InteropTests (SPM)
    runs-on: windows-2022
    timeout-minutes: 15

    steps:
    - uses: actions/checkout@v3
    - uses: ./.github/actions/setup-swift

    - name: Build code generator
      working-directory: Generator
      shell: pwsh
      run: swift build --verbose --build-tests

    - name: Test code generator
      working-directory: Generator
      shell: pwsh
      run: swift test --verbose --skip-build

    - name: Build Test WinRT Component
      working-directory: InteropTests
      shell: pwsh
      run: '& .\BuildAndGenerate.ps1'

    - name: Build InteropTests
      working-directory: InteropTests
      shell: pwsh
      run: swift build --verbose --build-tests

    - name: Run InteropTests
      working-directory: InteropTests
      shell: pwsh
      run: swift test --verbose --skip-build

  support-cmake:
    name: Support Module (CMake)
    runs-on: windows-2022
    timeout-minutes: 15

    steps:
    - uses: actions/checkout@v3
    - uses: ./.github/actions/setup-swift

    - name: CMake Configure
      shell: pwsh
      run: cmake --preset debug

    - name: CMake Build
      shell: pwsh
      run: cmake --build --preset debug

  generator-cmake:
    name: Generator (CMake)
    runs-on: windows-2022
    timeout-minutes: 15

    steps:
    - uses: actions/checkout@v3
    - uses: ./.github/actions/setup-swift

    - name: Configure Generator
      working-directory: Generator
      shell: pwsh
      run: cmake --preset debug

    - name: Build Generator
      working-directory: Generator
      shell: pwsh
      run: cmake --build --preset debug

    - name: Generate InteropTests Projection
      working-directory: InteropTests
      shell: pwsh
      run: cmake --preset debug -D SWIFT_WINRT_EXE=${Env:GITHUB_WORKSPACE}\Generator\build\debug\Sources\SwiftWinRT\SwiftWinRT.exe

    - name: Build InteropTests Projection
      working-directory: InteropTests
      shell: pwsh
      run: cmake --build --preset debug