#include "SWRT/windows/BaseTsd.h"
#include "SWRT/windows/combaseapi.h"
#include "SWRT/windows/guiddef.h"
#include "SWRT/windows/oaidl.h"
#include "SWRT/windows/objidl.h"
#include "SWRT/windows/oleauto.h"
#include "SWRT/windows/unknwn.h"