#include "SWRT/winapi/BaseTsd.h"
#include "SWRT/winapi/combaseapi.h"
#include "SWRT/winapi/guiddef.h"
#include "SWRT/winapi/oaidl.h"
#include "SWRT/winapi/objidl.h"
#include "SWRT/winapi/oleauto.h"
#include "SWRT/winapi/unknwn.h"